# Generated by Django 5.2.4 on 2025-07-10 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_customer', 'Can view customers'), ('can_edit_customers', 'Can edit customers'), ('can_delete_customers', 'Can delete customers')]},
        ),
    ]
